---

- hosts: engine
  remote_user: root
  pre_tasks:
    - name: install packages
      yum: name={{ item }} state=present
      with_items: '{{ packages if packages is defined else [] }}'
      when: '{{ packages is defined and packages|length > 0 }}'

    - name: authenticate to engine
      ovirt_auth:
        username: '{{ engine_username }}'
        password: '{{ admin_password }}'
        url: https://{{ engine_fqdn }}/ovirt-engine/api
        insecure: true
  roles:
    - { role: launch_vms, when: '{{ vms is defined }}' }
  post_tasks:
    - name: add created vms to the inventory
      add_host:
        groups: created_vms
        name: '{{ item.name }}'
        username: '{{ item.username if item.get("username") else username }}'
      with_items: '{{ vms }}'
      when: '{{ vms is defined }}'

- hosts: created_vms
  remote_user: '{{ username }}'
  gather_facts: no
  roles:
    - { role: wait_for_host_up, timeout: 600 }

- hosts: created_vms
  remote_user: '{{ username }}'
  gather_facts: no
  become: true
  roles:
    - { role: satellite_registration, when: '{{ register_to_satellite }}' }
    - { role: subscription, when: '{{ repositories|length > 0 }}' }
