# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.ssh.insert_key = false
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.provision :shell, :path => "centos_7_x.sh"

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.define :x1 do |x1|
    x1.vm.hostname = 'x1'
    x1.vm.network :private_network, :mac => "52:11:22:33:44:41", :ip => '192.168.33.11'
    x1.hostmanager.aliases = %w(x1.example.org)
  end

  config.vm.define :x2 do |x2|
    x2.vm.hostname = 'x2'
    x2.vm.network :private_network, :mac => "52:11:22:33:44:42", :ip => '192.168.33.12'
    x2.hostmanager.aliases = %w(x2.example.org)
  end

  config.vm.define :x3 do |x3|
    x3.vm.hostname = 'x3'
    x3.vm.network :private_network, :mac => "52:11:22:33:44:43", :ip => '192.168.33.13'
    x3.hostmanager.aliases = %w(x3.example.org)
  end

  config.vm.define :nfs do |nfs|
    nfs.vm.hostname = 'nfs'
    nfs.vm.network :private_network, :mac => "52:11:22:33:44:44", :ip => '192.168.33.14'
    nfs.hostmanager.aliases = %w(nfs.example.org)
    nfs.vm.provision :shell, :path => "setup_nfs_shares.sh"
    nfs.vm.provider :libvirt do |libvirt|
      libvirt.memory = 2048
      libvirt.cpus = 1
    end
  end


  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
    libvirt.memory = 8000
    libvirt.cpus = `grep -c ^processor /proc/cpuinfo`.to_i
  end

end
